# Generated by Django 4.2 on 2026-03-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('priority', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('due_date', models.DateField()),
            ],
            options={
                'db_table': 'tasks',
                'managed': False,
            },
        ),
    ]
